//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnlineShop_PetsBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Details()
        {
            this.Feedback_Details = new HashSet<Feedback_Details>();
            this.Order_Cart = new HashSet<Order_Cart>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Gender { get; set; }
        public Nullable<System.DateTime> Customer_DateOfBirth { get; set; }
        public string Customer_MobileNumber { get; set; }
        public string Customer_EmailId { get; set; }
        public string Customer_BillingAddress { get; set; }
        public string Customer_City { get; set; }
        public string Cusromer_State { get; set; }
        public string Customer_Pincode { get; set; }
        public string Customer_UserName { get; set; }
        public string Customer_Password { get; set; }
        public string Customer_ImagePath { get; set; }
        public string Customer_ImageName { get; set; }
        public Nullable<System.DateTime> Customer_ActivationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Details> Feedback_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Cart> Order_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
