//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnlineShop_PetsBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Details
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Pet_Id { get; set; }
        public string Feedback_Message { get; set; }
        public Nullable<double> Feedback_Rating { get; set; }
        public Nullable<System.DateTime> Feedback_Date { get; set; }
    
        public virtual Customer_Details Customer_Details { get; set; }
        public virtual Seller_Details Seller_Details { get; set; }
    }
}
