//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnlineShop_PetsBay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetsBayEntities : DbContext
    {
        public PetsBayEntities()
            : base("name=PetsBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessories_Details> Accessories_Details { get; set; }
        public virtual DbSet<Admin_Details> Admin_Details { get; set; }
        public virtual DbSet<Category_Details> Category_Details { get; set; }
        public virtual DbSet<Customer_Details> Customer_Details { get; set; }
        public virtual DbSet<Feedback_Details> Feedback_Details { get; set; }
        public virtual DbSet<Order_Cart> Order_Cart { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Pet_Details> Pet_Details { get; set; }
        public virtual DbSet<Seller_Details> Seller_Details { get; set; }
    }
}
