//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnlineShop_PetsBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Cart
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Pets_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Order_Quantity { get; set; }
        public Nullable<decimal> Order_Price { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.DateTime> Order_ShippingDate { get; set; }
        public Nullable<int> Order_Flag { get; set; }
        public Nullable<int> Order_Status { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        public virtual Customer_Details Customer_Details { get; set; }
        public virtual Pet_Details Pet_Details { get; set; }
    }
}
