//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsOnlineShop_PetsBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Pet_Id { get; set; }
        public string Order_Details_ShippingAddress { get; set; }
        public string Order_Details_ShippingCity { get; set; }
        public string Order_Details_ShippingState { get; set; }
        public string Order_Details_ShippingPincode { get; set; }
        public Nullable<System.DateTime> Order_Details_DeliveryDate { get; set; }
        public string Order_Details_ModeOfPayment { get; set; }
        public Nullable<decimal> Order_Details_TotalPrice { get; set; }
        public Nullable<int> Order_Details_Flag { get; set; }
    
        public virtual Customer_Details Customer_Details { get; set; }
        public virtual Pet_Details Pet_Details { get; set; }
    }
}
